<template id="#app">
  <div class="h-screen w-full flex flex-col justify-center bg-spotify">
    <div id="particles-js" class="h-60 w-full items-end justify-start flex">
      <div class="absolute border-2 bg-transparent z-20 border-dashed rounded-md pl-5 pr-5 pb-3 p-2 ml-12 mb-12">
        <span class="text-white text-4xl font-medium select-none">Privacy Policy </span>
      </div>
    </div>
    <div class="w-full h-full bg-gray-800">
      <div class="ml-12 mt-12 flex flex-col items-start justify-start text-white gap-y-3">
        <h4 class="text-xl font-medium">Collection, Storage and Processing of Information</h4>
        <div>We only collect information that you provide directly to us. This can be any interaction with our
          services, for example by using our service in any way.<br></div>

        <h4 class="text-xl font-medium">Use of Web Analytic Services</h4>
        <div><p>
          The following web analytic service is used to improve the user experience of our services: We use Google
          Analytics, a service for the marketing analysis of this website, of Google Inc. ("Google"). Google Analytics
          uses codes consisting of text and numbers, which will be stored on your computer and which allow for an
          analysis of the use of the Website ("Cookies"). The information generated by the Cookie about your use of
          the website (including your IP address) will be transferred to and stored by a Google Server. Google will
          use this information, to evaluate your use of the website, to prepare reports about the website activities
          for the website operators and to provide further services connected to the use of websites and the use of
          the internet. Google may transfer this information to third parties, if legally obliged to do so or if third
          parties process these data on behalf of Google. In no case, Google will connect your IP address with other
          data from Google. </p>
          <p>You can remove or deactivate such Cookies using the settings of your computer; in such a case you might
            not be able to fully use all functions of this website. By using this website or the Best Brokers iOS or
            Android app, you agree to the processing of your personal data by Google to the extent and purpose stated
            above. You can refuse to allow your data to be passed on by using a deactivation add-on for browsers under
            https://goo.gl/1yuGP2.</p></div>

        <h4 class="text-xl font-medium">Security</h4>
        <div>Scylly cannot warrant security or privacy for any data transmitted from or to our services, because
          the transmission of information via the internet is not completely secure. Still, we encrypt any
          communication between the app and our servers with state-of the art SSL encryption.
          <p>Scylly is based in Germany. The information we collect is processed in the European Union and
            governed by the applicable German law and European directives.</p></div>

        <h4 class="text-xl font-medium">Contact</h4>
        <div>If you have any further questions about the collection, use and processing of your personal data, please
          contact us directly at: eric.elflein@googlemail.com
        </div>

        <h4 class="text-xl font-medium">Last updated:</h4>
        <div>September 2021</div>
      </div>
    </div>
  </div>
</template>

<script>
import '../assets/particles.js'

export default {
  name: "Privacy",
  mounted() {
    window.particlesJS('particles-js', {
      "particles": {
        "number": {
          "value": 106,
          "density": {
            "enable": true,
            "value_area": 1042.21783956259
          }
        },
        "color": {
          "value": "#48e816"
        },
        "shape": {
          "type": "circle",
          "stroke": {
            "width": 0,
            "color": "#ff0000"
          },
          "polygon": {
            "nb_sides": 6
          },
          "image": {
            "src": "img/github.svg",
            "width": 70,
            "height": 100
          }
        },
        "opacity": {
          "value": 0.5,
          "random": false,
          "anim": {
            "enable": true,
            "speed": 1,
            "opacity_min": 0.1,
            "sync": false
          }
        },
        "size": {
          "value": 3,
          "random": true,
          "anim": {
            "enable": true,
            "speed": 12.181158184520175,
            "size_min": 0.1,
            "sync": false
          }
        },
        "line_linked": {
          "enable": true,
          "distance": 150,
          "color": "#ffffff",
          "opacity": 0.4,
          "width": 1
        },
        "move": {
          "enable": true,
          "speed": 6,
          "direction": "none",
          "random": false,
          "straight": false,
          "out_mode": "out",
          "bounce": false,
          "attract": {
            "enable": false,
            "rotateX": 600,
            "rotateY": 1200
          }
        }
      },
      "interactivity": {
        "detect_on": "window",
        "events": {
          "onhover": {
            "enable": true,
            "mode": "grab"
          },
          "onclick": {
            "enable": true,
            "mode": "push"
          },
          "resize": true
        },
        "modes": {
          "grab": {
            "distance": 158.35505639876231,
            "line_linked": {
              "opacity": 1
            }
          },
          "bubble": {
            "distance": 400,
            "size": 40,
            "duration": 2,
            "opacity": 8,
            "speed": 3
          },
          "repulse": {
            "distance": 200,
            "duration": 0.4
          },
          "push": {
            "particles_nb": 4
          },
          "remove": {
            "particles_nb": 2
          }
        }
      },
      "retina_detect": true
    })
  }
}
</script>

<style scoped>

</style>